name: "Build main"

on:
  push:
    branches:
      - main

env:
  JAVA_OPTS: -Xms512m -Xmx1024m
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.configureondemand=true -Dorg.gradle.jvmargs=-Xmx3g -XX:MaxPermSize=2048m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"
  SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
  SONATYPE_PWD: ${{ secrets.SONATYPE_PWD }}
  SIGNINGKEY: ${{ secrets.SIGNINGKEY }}
  SIGNINGPASSWORD: ${{ secrets.SIGNINGPASSWORD }}

jobs:
  publish_jvm_js_linux_apple:
    env:
      SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
      SONATYPE_PWD: ${{ secrets.SONATYPE_PWD }}

    runs-on: macos-latest
    timeout-minutes: 120

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      -  name: Setup JDK
         uses: actions/setup-java@v2
         with:
           distribution: 'zulu'
           java-version: '8'

      - name: Build
        run: ./gradlew publishToSonatype --scan --stacktrace
  publish_windows:
    env:
      SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
      SONATYPE_PWD: ${{ secrets.SONATYPE_PWD }}

    runs-on: windows-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build
        run: ./gradlew publishToSonatype --scan --stacktrace
